import { LayoutAuthComponent } from './layout-auth/layout-auth.component';
import { LayoutDashboardComponent } from './layout-dashboard/layout-dashboard.component';
import { LayoutErrorComponent } from './layout-error/layout-error.component';
import { LayoutSelfServiceComponent } from './layout-self-service/layout-self-service.component';
import { LayoutMyTeamComponent } from './layout-my-team/layout-my-team.component';
import { LayoutCheckInComponent } from './layout-check-in/layout-check-in.component';
import { LayoutCheckOutComponent } from './layout-check-out/layout-check-out.component';
import { LayoutMyRequestComponent } from './layout-my-request/layout-my-request.component';
import { LayoutTimesheetComponent } from './layout-timesheet/layout-timesheet.component';
import { LayoutApprovalComponent } from './layout-approval/layout-approval.component';
import { LayoutSettingsComponent } from './layout-settings/layout-settings.component';
import { LayoutReportsComponent } from './layout-reports/layout-reports.component';
import { LayoutProfileComponent } from './layout-profile/layout-profile.component';
import { LayoutEmploymentComponent } from './layout-employment/layout-employment.component';
import { LayoutAddressComponent } from './layout-address/layout-address.component';
import { LayoutFamilyComponent } from './layout-family/layout-family.component';

export const layouts = [LayoutDashboardComponent, LayoutAuthComponent, LayoutErrorComponent, LayoutSelfServiceComponent, LayoutMyTeamComponent, LayoutCheckInComponent, LayoutCheckOutComponent, LayoutMyRequestComponent, LayoutTimesheetComponent, LayoutApprovalComponent, LayoutSettingsComponent, LayoutReportsComponent, LayoutProfileComponent, LayoutEmploymentComponent, LayoutAddressComponent, LayoutFamilyComponent];

export * from './layout-dashboard/layout-dashboard.component';
export * from './layout-auth/layout-auth.component';
export * from './layout-error/layout-error.component';
export * from './layout-self-service/layout-self-service.component';
export * from './layout-my-team/layout-my-team.component';
export * from './layout-check-in/layout-check-in.component';
export * from './layout-check-out/layout-check-out.component';
export * from './layout-my-request/layout-my-request.component';
export * from './layout-timesheet/layout-timesheet.component';
export * from './layout-approval/layout-approval.component';
export * from './layout-settings/layout-settings.component';
export * from './layout-reports/layout-reports.component';
export * from './layout-profile/layout-profile.component';
export * from './layout-employment/layout-employment.component';
export * from './layout-address/layout-address.component';
export * from './layout-family/layout-family.component';
